[2022-10-07T02:44:09.159+0000] {processor.py:156} INFO - Started process (PID=2814) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:44:09.160+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:44:09.162+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:44:09.162+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:44:09.664+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:44:09.681+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:44:09.676+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:44:09.683+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:44:09.722+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.567 seconds
[2022-10-07T02:44:40.196+0000] {processor.py:156} INFO - Started process (PID=2870) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:44:40.197+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:44:40.198+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:44:40.198+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:44:40.636+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:44:40.648+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:44:40.644+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:44:40.649+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:44:40.695+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.502 seconds
[2022-10-07T02:45:11.695+0000] {processor.py:156} INFO - Started process (PID=2935) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:45:11.697+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:45:11.698+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:45:11.698+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:45:12.283+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:45:12.297+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:45:12.292+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:45:12.301+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:45:12.326+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.635 seconds
[2022-10-07T02:45:43.170+0000] {processor.py:156} INFO - Started process (PID=3000) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:45:43.171+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:45:43.173+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:45:43.172+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:45:43.597+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:45:43.605+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:45:43.602+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:45:43.606+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:45:43.624+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.458 seconds
[2022-10-07T02:46:14.307+0000] {processor.py:156} INFO - Started process (PID=3056) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:46:14.308+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:46:14.309+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:46:14.309+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:46:14.839+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:46:14.851+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:46:14.846+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:46:14.852+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:46:14.872+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.567 seconds
[2022-10-07T02:46:45.691+0000] {processor.py:156} INFO - Started process (PID=3121) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:46:45.692+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:46:45.693+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:46:45.693+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:46:46.205+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:46:46.218+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:46:46.213+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:46:46.220+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:46:46.248+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.562 seconds
[2022-10-07T02:47:16.914+0000] {processor.py:156} INFO - Started process (PID=3186) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:47:16.915+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:47:16.917+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:47:16.916+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:47:17.312+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:47:17.323+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:47:17.318+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:47:17.324+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:47:17.349+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.440 seconds
[2022-10-07T02:47:47.470+0000] {processor.py:156} INFO - Started process (PID=3242) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:47:47.472+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:47:47.473+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:47:47.473+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:47:47.961+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:47:47.974+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:47:47.968+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:47:47.975+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:47:48.004+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.537 seconds
[2022-10-07T02:48:18.236+0000] {processor.py:156} INFO - Started process (PID=3308) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:48:18.238+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:48:18.239+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:48:18.238+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:48:18.699+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:48:18.712+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:48:18.707+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:48:18.714+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:48:18.742+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.509 seconds
[2022-10-07T02:48:48.986+0000] {processor.py:156} INFO - Started process (PID=3364) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:48:48.987+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:48:48.988+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:48:48.988+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:48:49.496+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:48:49.509+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:48:49.504+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:48:49.511+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:48:49.541+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.558 seconds
[2022-10-07T02:49:20.031+0000] {processor.py:156} INFO - Started process (PID=3429) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:49:20.032+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:49:20.033+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:49:20.033+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:49:20.536+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:49:20.547+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:49:20.541+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:49:20.548+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:49:20.573+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.545 seconds
[2022-10-07T02:49:51.325+0000] {processor.py:156} INFO - Started process (PID=3487) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:49:51.327+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:49:51.329+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:49:51.328+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:49:51.921+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:49:51.936+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:49:51.930+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:49:51.939+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:49:51.975+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.658 seconds
[2022-10-07T02:50:22.206+0000] {processor.py:156} INFO - Started process (PID=3550) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:50:22.207+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:50:22.208+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:50:22.208+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:50:22.607+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:50:22.618+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:50:22.615+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:50:22.619+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:50:22.641+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.437 seconds
[2022-10-07T02:50:53.039+0000] {processor.py:156} INFO - Started process (PID=3614) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:50:53.042+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:50:53.043+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:50:53.043+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:50:53.535+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:50:53.547+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:50:53.542+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:50:53.549+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:50:53.580+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.547 seconds
[2022-10-07T02:51:24.525+0000] {processor.py:156} INFO - Started process (PID=3670) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:51:24.527+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:51:24.528+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:51:24.528+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:51:24.999+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:51:25.013+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:51:25.008+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:51:25.015+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:51:25.053+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.532 seconds
[2022-10-07T02:51:55.548+0000] {processor.py:156} INFO - Started process (PID=3735) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:51:55.550+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:51:55.551+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:51:55.551+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:51:56.084+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:51:56.097+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:51:56.091+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:51:56.100+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:51:56.126+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.583 seconds
[2022-10-07T02:52:26.253+0000] {processor.py:156} INFO - Started process (PID=3791) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:52:26.255+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:52:26.256+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:52:26.256+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:52:26.762+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:52:26.777+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:52:26.772+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:52:26.779+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:52:26.821+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.572 seconds
[2022-10-07T02:52:57.103+0000] {processor.py:156} INFO - Started process (PID=3856) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:52:57.105+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:52:57.107+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:52:57.107+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:52:57.654+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:52:57.666+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:52:57.661+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:52:57.668+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:52:57.692+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.593 seconds
[2022-10-07T02:53:27.807+0000] {processor.py:156} INFO - Started process (PID=3912) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:53:27.808+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:53:27.809+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:53:27.809+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:53:28.383+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:53:28.396+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:53:28.390+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:53:28.398+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:53:28.440+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.637 seconds
[2022-10-07T02:53:59.285+0000] {processor.py:156} INFO - Started process (PID=3977) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:53:59.286+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:53:59.287+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:53:59.287+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:53:59.821+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:53:59.831+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:53:59.827+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:53:59.833+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:53:59.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.575 seconds
[2022-10-07T02:54:29.955+0000] {processor.py:156} INFO - Started process (PID=4042) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:54:29.956+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:54:29.957+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:54:29.957+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:54:30.425+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:54:30.436+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:54:30.431+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:54:30.438+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:54:30.474+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.523 seconds
[2022-10-07T02:55:01.131+0000] {processor.py:156} INFO - Started process (PID=4098) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:55:01.133+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:55:01.135+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:55:01.135+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
[2022-10-07T02:55:01.612+0000] {logging_mixin.py:117} INFO - Error No module named 'scraper'
[2022-10-07T02:55:01.624+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:55:01.619+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/testDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testDag.py", line 61, in <module>
    python_callable=final_df
NameError: name 'final_df' is not defined
[2022-10-07T02:55:01.626+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/testDag.py
[2022-10-07T02:55:01.660+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/testDag.py took 0.533 seconds
[2022-10-07T02:55:31.779+0000] {processor.py:156} INFO - Started process (PID=4163) to work on /opt/airflow/dags/testDag.py
[2022-10-07T02:55:31.784+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/testDag.py for tasks to queue
[2022-10-07T02:55:31.789+0000] {logging_mixin.py:117} INFO - [2022-10-07T02:55:31.789+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/testDag.py
